version: "3.4"

services:
  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./API_EJEMPLO/init:/docker-entrypoint-initdb.d
      - ./API_PREGUNTAS/init.sql:/docker-entrypoint-initdb.d/02-init.sql
      - ./API_RESPUESTASESTUDIANTES/init.sql:/docker-entrypoint-initdb.d/03-init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20

# Frontend con Next.js
  frontend:
    build: 
      context: ./frontend-prototipos
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-prototipos/src:/app/src
      - ./frontend-prototipos/public:/app/public
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    restart: always

#Api de preguntas
  api_preguntas:
    build: ./API_PREGUNTAS
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=preguntas
      - PORT_API=8080
    depends_on:
      mysql:
        condition: service_healthy

#Api de respuestas
  api_respuestas:
    build: ./API_RESPUESTASESTUDIANTES
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=respuestas
      - PORT_API=8081
    depends_on:
      mysql:
        condition: service_healthy
