version: "3.4"

services:
  api_preguntas:
    image: api_preguntas
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
  
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


